# Generated by Django 2.0.7 on 2019-05-13 17:02

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190513_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('video', models.FileField(upload_to=quiz.models.upload_location_for_music)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_text', models.CharField(max_length=200, unique=True)),
                ('image', models.FileField(default='', upload_to=quiz.models.upload_location_for_subject)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnamese', models.CharField(max_length=20)),
                ('english', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to=quiz.models.upload_location_for_word)),
                ('audio', models.FileField(upload_to=quiz.models.upload_location_for_word)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Subject')),
            ],
        ),
    ]
