# Generated by Django 2.0.7 on 2019-05-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_music_subject_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_text',
            new_name='subject',
        ),
    ]
