# Generated by Django 2.0.7 on 2019-05-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190514_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='vietnamese',
            field=models.CharField(max_length=200),
        ),
    ]
