# Generated by Django 2.0.7 on 2019-05-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190514_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Question')),
            ],
        ),
    ]
