# Generated by Django 2.0.7 on 2019-05-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_questionattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='correctAnswer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='isCorrectAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
