# Generated by Django 2.0.7 on 2019-05-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190516_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='isCorrectAnswer',
            field=models.BooleanField(default=False, verbose_name='Correct answer ?'),
        ),
    ]
