# Generated by Django 2.0.7 on 2019-05-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20190516_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='isCorrectAnswer',
        ),
    ]
