# Generated by Django 2.0.7 on 2019-05-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_questionattempt_iscorrectanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='isCorrectAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
