# Generated by Django 2.0.7 on 2019-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20190516_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='answer',
            field=models.CharField(default='default value', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='correctAnswer',
            field=models.CharField(default='default value', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='question',
            field=models.CharField(default='default value', max_length=200),
        ),
    ]
